spring.application.name=homework

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/homework
spring.datasource.username=postgres
spring.datasource.password=root

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml