spring.application.name=homework

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d7j5aqvaqgkc73ablqpg-a.frankfurt-postgres.render.com/homework_5jyv
spring.datasource.username=user
spring.datasource.password=3eWpPGiMbF6Hor00ghMZ7ChOvRAXvDdl

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

